####   ###  ####  #   #  ####  #    # ####
#   # #   # #   # #  #  #    # #    # #   #
####  ##### ####  ###   #    # #    # ####
#     #   # #   # #  #  #    # #    # #   #
#     #   # #   # #   #  ####   ####  #   #
name: Parkour
main: io.github.hiwiscifi.mc.plugins.parkour.Main
version: 1.0
api-version: 1.16

 ####  ####  #    # #    #  ###  #   # ####   ####
#     #    # ##  ## ##  ## #   # ##  # #   # #
#     #    # # ## # # ## # ##### # # # #   #  ####
#     #    # #    # #    # #   # #  ## #   #      #
 ####  ####  #    # #    # #   # #   # ####   ####
commands:
    test:
        description: A test command
        usage: /test
        permission: io.github.hiwiscifi.mc.plugins.parkour.commands.test
    holo:
        description: Create a holographic text
        usage: /holo <create>
        permission: io.github.hiwiscifi.mc.plugins.parkour.commands.holo
    parkour:
        description: Do cool stuff
        usage: /parkour
        permission: io.github.hiwiscifi.mc.plugins.parkour.commands.parkour

####  ##### ####  #    # ###  ####   ####  ###  ####  #   #  ####
#   # #     #   # ##  ##  #  #      #       #  #    # ##  # #
####  ####  ####  # ## #  #   ####   ####   #  #    # # # #  ####
#     #     #   # #    #  #       #      #  #  #    # #  ##      #
#     ##### #   # #    # ###  ####   ####  ###  ####  #   #  ####
permissions:
    io.github.hiwiscifi.mc.plugins.parkour.commands.test:
        description: use the test command
        default: true # true | op
    io.github.hiwiscifi.mc.plugins.parkour.commands.holo:
        description: use the holo command
        default: op
    io.github.hiwiscifi.mc.plugins.parkour.commands.parkour:
        description: use the parkour command
        default: op